name: "apollo-server"

networks:
  apollo-server-network:

volumes:
  development:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "1300:5000"
    networks:
      - apollo-server-network
