name: "apollo-server"

networks:
  apollo-server-network:

volumes:
  development:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "1300:5000"
    networks:
      - apollo-server-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "1301:5432"
    volumes:
      - development:/data/apollo-postgres
      - ./db/schema/:/docker-entrypoint-initdb.d/
      - ./db/conf/:/etc/postgres/conf/
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - apollo-server-network
    command: ["postgres", "-c", "config_file=/etc/postgres/conf/postgresql.conf"]

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "1302:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=i.acnaylor@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=my_pg_password!
    networks:
      - apollo-server-network
