name: "apollo-server"

networks:
  apollo_net:
    name: "apollo-network"
  db_net:
    name: "database-network"
    external: true

volumes:
  development:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APOLLO_ENV="prod"
    env_file:
      - .env
      - .env.docker
    ports:
      - "1300:5000"
    networks:
      - apollo_net

  database:
    image: postgres:latest
    restart: always
    ports:
      - "${APOLLO_DB_HOST_PORT}:5432"
    volumes:
      - development:/data/apollo-db
      - ./sql/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=${APOLLO_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${APOLLO_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - apollo_net
      - db_net
