name: Bun build

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  cache: "bun"
            - run: bun ci
            - run: bun run build --if-present
            - run: bun run lint
